# Generated by Django 4.0.3 on 2022-03-31 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('up_down', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.article')),
                ('webuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.webuser')),
            ],
            options={
                'unique_together': {('webuser', 'article')},
            },
        ),
    ]
