# Generated by Django 4.0.3 on 2022-04-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_collect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=255)),
                ('star', models.CharField(max_length=50)),
                ('birth', models.DateTimeField(max_length=50)),
                ('habit', models.CharField(max_length=255)),
                ('school', models.CharField(max_length=127)),
                ('location', models.CharField(max_length=127)),
                ('webuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.webuser')),
            ],
            options={
                'db_table': 'info',
            },
        ),
    ]
