# Generated by Django 4.0.3 on 2022-04-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='birth',
            field=models.DateTimeField(max_length=50, null=True),
        ),
    ]
